# Use: docker compose -f .docker/docker-compose.yaml -f .docker/docker-compose.dev.yaml up
name: openfga-dev
services:
  migrate:
    build:
      context: ..

  openfga:
    build:
      context: ..
    environment:
      - OPENFGA_TRACE_SAMPLE_RATIO=1
      - OPENFGA_PROFILER_ENABLED=true
    ports:
      - "3002:3001" #profiler (port 3001 is exposed for Grafana)